version: '3'
services:

  cassandra1: 
    image: cassandra:3.11.3
    container_name: cassandra1
    volumes: 
     - "/home/workspace-compose/cassandra/volume/conf/cassandra-3.11.3.yaml:/etc/cassandra/cassandra.yaml" 
     - "/home/workspace-compose/cassandra/volume/data:/home/cassandra/data" 
     - "/home/workspace-compose/cassandra/volume/commitlog:/home/cassandra/commitlog" 
     - "/home/workspace-compose/cassandra/volume/saved_caches:/home/cassandra/saved_caches" 
#    environment:
#      CASSANDRA_LISTEN_ADDRESS: 
    network_mode: "host"
    privileged: true
