version: '3'
services:

#docker run -it -d --net=host --name j1 -v /home/workspace-compose/java/2-config/volume/lib:/home/java/lib -v /home/workspace-compose/java/2-config/volume/logs:/logs java java -Xms128m -Xmx256m -jar /home/java/lib/config-service-0.0.1-SNAPSHOT.jar --server.port=11001

  config-service1: 
    image: java
    container_name: config-service1
    volumes: 
     - "/home/workspace-compose/java/2-config/volume/lib:/home/java/lib"
     - "/home/workspace-compose/java/2-config/volume/config-center/11001:/home/java/config-center"
     - "/home/workspace-compose/java/2-config/volume/logs/11001:/logs"
    network_mode: "host"
    command: java -Xms128m -Xmx256m -jar /home/java/lib/config-service-0.0.1-SNAPSHOT.jar --server.port=11001
  
  config-service2: 
    image: java
    container_name: config-service2
    volumes: 
     - "/home/workspace-compose/java/2-config/volume/lib:/home/java/lib"
     - "/home/workspace-compose/java/2-config/volume/config-center/11002:/home/java/config-center"
     - "/home/workspace-compose/java/2-config/volume/logs/11002:/logs"
    network_mode: "host"
    command: java -Xms128m -Xmx256m -jar /home/java/lib/config-service-0.0.1-SNAPSHOT.jar --server.port=11002
    
  config-service3: 
    image: java
    container_name: config-service3
    volumes: 
     - "/home/workspace-compose/java/2-config/volume/lib:/home/java/lib"
     - "/home/workspace-compose/java/2-config/volume/config-center/11003:/home/java/config-center"
     - "/home/workspace-compose/java/2-config/volume/logs/11003:/logs"
    network_mode: "host"
    command: java -Xms128m -Xmx256m -jar /home/java/lib/config-service-0.0.1-SNAPSHOT.jar --server.port=11003