version: '3'
services:
  zoo1:
    image: wurstmeister/zookeeper
    container_name: zoo1
    privileged: true
    ports:
     - "2181:2181"
    networks:
      net-kafk:  
        ipv4_address: 172.100.0.2
        
  kafk1:
    image: wurstmeister/kafka
    container_name: kafk1
    privileged: true
    ports:
     - "9092:9092"
    networks:
      net-kafk:  
        ipv4_address: 172.100.0.11
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 172.100.0.11
      KAFKA_ADVERTISED_PORT: 9092 
      KAFKA_ZOOKEEPER_CONNECT: "172.100.0.2:2181" 
      KAFKA_BROKER_ID: 2 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
    depends_on: 
     - zoo1

 

networks:
  net-kafk: 
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.100.0.0/24