FROM java:8
MAINTAINER 312012733 "312012733@qq.com"

ENV FFMPEG_VERSION 4.0.3

WORKDIR /tmp

RUN wget -q https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.0.3-64bit-static.tar.xz \
  && tar xJf /tmp/ffmpeg-4.0.3-64bit-static.tar.xz -C /tmp \
  && mv /tmp/ffmpeg-4.0.3-64bit-static/ffmpeg /usr/local/bin/ \
  && rm -rf /tmp/ffmpeg*

# CentOS
RUN echo "Asia/shanghai" > /etc/timezone;

# Ubuntu
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime










