version: '3'
services:
  j1:
    image: java
#    build:
#      context: .
#      dockerfile: Dockerfile-java
    container_name: j1
    volumes: 
     - "/home/spring-cloud-compose/java:/home/soft"
     - "j1-log:/logs"
    network_mode: "host"
    privileged: true
    command: nohup java -Xms128m -Xmx256m -jar /home/soft/renren-fast.jar --server.port=19001 >>/logs/renren-fast-19001.log 2>&1 &
    ports:
     - "19001:19001"
    networks:
      net-java:
        ipv4_address: 172.100.10.1
        
  j2:
    image: java
    container_name: j2
    volumes: 
     - "/home/spring-cloud-compose/java:/home/soft"
     - "j2-log:/logs"
    network_mode: "host"
    command: java -Xms128m -Xmx256m -jar /home/soft/renren-fast.jar --server.port=19002  

volumes:
  j1-log:
  j2-log:
  
networks:
  net1: 
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.90.0.0/24
  net2: 
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.100.0.0/24