version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    container_name: j1
  redis:
    image: "redis:alpine"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
