version: '3'
services:
  j1:
    image: java
    container_name: j1
    command: nohup java -Xms128m -Xmx256m -jar /home/soft/renren-fast.jar --server.port=19001 >> /home/soft/renren-fast-19001.log 2>&1 &
    volumes: 
     - "/home/java-service-compose/java:/home/soft"
    network_mode: "host"
#    ports:
#     - "19001:19001"
#    networks:
#      net-java:
#        ipv4_address: 172.100.10.1
  j2:
    image: java
    container_name: j2
    command: nohup java -Xms128m -Xmx256m -jar /home/soft/renren-fast.jar --server.port=19002 >>/home/soft/renren-fast-19002.log 2>&1 &
    volumes: 
     - "/home/java-service-compose/java:/home/soft"
    network_mode: "host"
  j3: 
    image: java
    container_name: j3
    command: nohup java -Xms128m -Xmx256m -jar /home/soft/renren-fast.jar --server.port=19003 >> /home/soft/renren-fast-19003.log 2>&1 &
    volumes: 
     - "/home/java-service-compose/java:/home/soft"
    network_mode: "host"
  jn1: 
    image: nginx
    container_name: jn1
    command: nginx
    volumes: 
     - "/home/java-service-compose/nginx/n1/nginx.conf:/etc/nginx/nginx.conf"
    network_mode: "host"
#    ports:
#     - "6001:6001"
#    networks:
#      net-java:
#        ipv4_address: 172.100.90.1
  jn2: 
    image: nginx
    container_name: jn2
    command: nginx
    volumes:
     - "/home/java-service-compose/nginx/n2/nginx.conf:/etc/nginx/nginx.conf"
    network_mode: "host"
    
#volumes:
#  jarlib:

#networks:
#  net-java:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      -
#        subnet: 172.100.0.0/24
