version: '3'
services:
  zookeeper1:
    #image: wurstmeister/zookeeper
    image: zookeeper:3.4.13
    container_name: zookeeper1
    privileged: true
    network_mode: "host"
    volumes: 
     - "/home/workspace-compose/kafka/volume/zookeeper/data:/data"
     - "/home/workspace-compose/kafka/volume/zookeeper/datalog:/datalog"
#     - "/home/workspace-compose/kafka/volume/zookeeper/conf/zoo.cfg:/conf/zoo.cfg 

        
  kafka1:
    image: wurstmeister/kafka:2.12-2.1.0
    container_name: kafka1
    privileged: true
    network_mode: "host"
    volumes: 
     - "/home/workspace-compose/kafka/volume/kafka/logs:/home/kafka/logs"
    environment: 
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.3.241
#      KAFKA_ADVERTISED_PORT: 9092 
      KAFKA_LISTENERS: PLAINTEXT://192.168.3.241:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.3.241:9092
      KAFKA_ZOOKEEPER_CONNECT: "192.168.3.241:2181" 
      KAFKA_LOG_DIRS: /home/kafka/logs
      KAFKA_BROKER_ID: 2 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
    depends_on: 
     - zookeeper1

