version: '3'
services:
  zookeeper1:
    image: wurstmeister/zookeeper
    container_name: zookeeper1
    privileged: true
    network_mode: "host"

        
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    privileged: true
    network_mode: "host"

    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092 
      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:2181" 
      KAFKA_BROKER_ID: 2 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
    depends_on: 
     - zoo1

