version: '3'
services:

  rabbitmq1: 
    image: rabbitmq:3.7.8-management
    container_name: rabbitmq1
    hostname: rabbitmq1 #port:5672  15672
    network_mode: "host"
    privileged: true
    volumes: 
     - "/home/workspace-compose/rabbitmq/volume/data:/var/lib/rabbitmq" 
#     - "/home/workspace-compose/rabbitmq/volume/conf/rabbitmq-3.7.8.conf:/etc/rabbitmq/rabbitmq.conf" 
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.4
      RABBITMQ_DEFAULT_VHOST: my_vhost
